"""add finding assignment

Revision ID: 1599ea7d6245
Revises: 802cc17b4d5e
Create Date: 2026-08-21 16:58:16.210832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1599ea7d6245'
down_revision: Union[str, Sequence[str], None] = '802cc17b4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_findings', sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_security_findings_assigned_to_user_id'), 'security_findings', ['assigned_to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_findings_assigned_to_user_id'), table_name='security_findings')
    op.drop_column('security_findings', 'assigned_to_user_id')
    # ### end Alembic commands ###
