"""add unique finding evidence constraint

Revision ID: 333fbab4d48a
Revises: e6f425111b0e
Create Date: 2026-08-11 01:56:20.049364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333fbab4d48a'
down_revision: Union[str, Sequence[str], None] = 'e6f425111b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_finding_evidence_finding_audit_event', 'finding_evidence', ['finding_id', 'audit_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_finding_evidence_finding_audit_event', 'finding_evidence', type_='unique')
    # ### end Alembic commands ###
