"""add audit event metadata

Revision ID: 4ddd60e8e49f
Revises: 63392965cc2b
Create Date: 2026-08-11 00:11:18.337477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddd60e8e49f'
down_revision: Union[str, Sequence[str], None] = '63392965cc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('event_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'event_metadata')
    # ### end Alembic commands ###
