"""prevent duplicate running ai triage

Revision ID: 5dfa38a33ff5
Revises: eaab78c8ff2e
Create Date: 2026-08-29 02:04:22.254646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfa38a33ff5'
down_revision: Union[str, Sequence[str], None] = 'eaab78c8ff2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_ai_triage_runs_one_running_per_finding', 'ai_triage_runs', ['finding_id'], unique=True, postgresql_where=sa.text("status = 'running'"), sqlite_where=sa.text("status = 'running'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ai_triage_runs_one_running_per_finding', table_name='ai_triage_runs', postgresql_where=sa.text("status = 'running'"), sqlite_where=sa.text("status = 'running'"))
    # ### end Alembic commands ###
