"""create security findings table

Revision ID: 63392965cc2b
Revises: 7f07ec213a98
Create Date: 2026-08-10 00:53:10.543820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63392965cc2b'
down_revision: Union[str, Sequence[str], None] = '7f07ec213a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_type', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_findings_finding_type'), 'security_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_security_findings_status'), 'security_findings', ['status'], unique=False)
    op.create_index(op.f('ix_security_findings_subject'), 'security_findings', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_findings_subject'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_status'), table_name='security_findings')
    op.drop_index(op.f('ix_security_findings_finding_type'), table_name='security_findings')
    op.drop_table('security_findings')
    # ### end Alembic commands ###
