"""create analyst notes

Revision ID: 802cc17b4d5e
Revises: 9cdb2e40b8d5
Create Date: 2026-08-21 01:25:39.665635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802cc17b4d5e'
down_revision: Union[str, Sequence[str], None] = '9cdb2e40b8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['security_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_notes_author_user_id'), 'analyst_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_analyst_notes_finding_id'), 'analyst_notes', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyst_notes_finding_id'), table_name='analyst_notes')
    op.drop_index(op.f('ix_analyst_notes_author_user_id'), table_name='analyst_notes')
    op.drop_table('analyst_notes')
    # ### end Alembic commands ###
