"""create ai triage runs

Revision ID: 9cdb2e40b8d5
Revises: 5ef51409203b
Create Date: 2026-08-16 01:44:33.947471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdb2e40b8d5'
down_revision: Union[str, Sequence[str], None] = '5ef51409203b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_triage_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('analyst_assessment', sa.Text(), nullable=False),
    sa.Column('confirmed_facts', sa.JSON(), nullable=False),
    sa.Column('hypotheses', sa.JSON(), nullable=False),
    sa.Column('missing_context', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('compromise_status', sa.String(length=30), nullable=False),
    sa.Column('grounding_corrections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['security_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_triage_runs_finding_id'), 'ai_triage_runs', ['finding_id'], unique=False)
    op.create_index(op.f('ix_ai_triage_runs_requested_by_user_id'), 'ai_triage_runs', ['requested_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_triage_runs_requested_by_user_id'), table_name='ai_triage_runs')
    op.drop_index(op.f('ix_ai_triage_runs_finding_id'), table_name='ai_triage_runs')
    op.drop_table('ai_triage_runs')
    # ### end Alembic commands ###
