"""add finding evidence and rule id

Revision ID: e6f425111b0e
Revises: 4ddd60e8e49f
Create Date: 2026-08-11 01:42:40.558111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f425111b0e'
down_revision: Union[str, Sequence[str], None] = '4ddd60e8e49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('audit_event_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_event_id'], ['audit_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['security_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_evidence_audit_event_id'), 'finding_evidence', ['audit_event_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_finding_id'), 'finding_evidence', ['finding_id'], unique=False)
    op.add_column('security_findings', sa.Column('rule_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_security_findings_rule_id'), 'security_findings', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_findings_rule_id'), table_name='security_findings')
    op.drop_column('security_findings', 'rule_id')
    op.drop_index(op.f('ix_finding_evidence_finding_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_audit_event_id'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    # ### end Alembic commands ###
